### ISSUE TITLE
uialertcontroller bug

### ISSUE THREAD

**Issue by gongqiuwei** [cdpenggod/CDPMonitorKeyboard#1]
没有收回键盘，如果在弹出UIalertcontroller 会出现bug， xcode提示： [UIAlertController superview]: unrecognized selector sent to instance 0x7ff0fb533840 堆栈：在附近中
![snip20180411_1](https://user-images.githubusercontent.com/3827831/38593615-cce450d0-3d74-11e8-8c19-3e14406757fb.png)
![snip20180411_2](https://user-images.githubusercontent.com/3827831/38593617-d92dfcc4-3d74-11e8-9501-f952300b741a.png)
![snip20180411_3](https://user-images.githubusercontent.com/3827831/38593620-db78f9a2-3d74-11e8-8a82-0cd2f5d0ef70.png)

UIView *view=[self getResponderViewWithMode:CDPMonitorKeyboardDefaultMode];查找到的不一定是view

**Comment by cdpenggod** [comment]
已经解决，谢谢反馈 @gongqiuwei
